name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn lint
    - run: yarn lintsass
    - run: yarn build:prod
